pages:
  stage: deploy
  script:
    - echo "Generating Javadoc..."
    - mkdir -p public
    - javadoc -d public -sourcepath src -subpackages fr.inria.boreal.jfbaget.irirefs
  artifacts:
    paths:
      - public
  only:
    - main
  tags:
    - ci.inria.fr